# Dockerfile for Weather Vane backend API application

FROM node:lts-alpine as builder

WORKDIR /app

COPY src/vue/weathervane-ui/package*.json ./

RUN npm install

COPY src/vue/weathervane-ui/ .

RUN npm run build

FROM nginx:alpine as prod-build

COPY nginx.conf /etc/nginx/nginx.conf

RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 8080

CMD [ "nginx", "-g", "daemon off;" ]
