# syntax=docker/dockerfile:1

FROM python:3.8-slim-buster

WORKDIR /weathervane

COPY src/python/requirements.txt requirements.txt
COPY src/python/weathervane-api /weathervane/

RUN pip3 install -r requirements.txt

ENV PORT 8080

#CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0", "--port=8080" ]
CMD exec gunicorn --bind :$PORT --workers 1 --threads 8 app
