version: '3'
services:
  wv-api:
    image: weathervane-api:latest
    ports:
      - "5000:8080"
    environment:
      - GMAPS_API_KEY=${GMAPS_API_KEY}
      - WEATHER_API_KEY=${WEATHER_API_KEY}
    networks:
      - app-network
  wv-ui:
    image: weathervane-ui:latest
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network: {}
